<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="12" ignored="0" total="44" passed="32">
  <reporter-output>
    <line>
      <![CDATA[Tests are going to be run...
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:&lt;email@domain.com&gt;]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Name only contains spaces]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Phone:+905552+133]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Address only contains spaces]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form wasn't submitted, but it should be submitted Email:email@[123.123.123.123]]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:.email@domain.com]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Phone:055Letter511223365]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form wasn't submitted, but it should be submitted Email:"email"@domain.com]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:email.@domain.com]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:email..email@domain.com]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Phone:Letter009055004455]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:email@-domain.com]]>
    </line>
    <line>
      <![CDATA[Test has failed.
]]>
    </line>
    <line>
      <![CDATA[Test has started. 
]]>
    </line>
    <line>
      <![CDATA[Test has passed. 
]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="495241" started-at="2022-01-20T21:30:55Z" finished-at="2022-01-20T21:39:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="495241" started-at="2022-01-20T21:30:55Z" finished-at="2022-01-20T21:39:10Z">
      <class name="automation.GeneralTest">
        <test-method status="PASS" signature="bfClass()[pri:0, instance:automation.GeneralTest@5025a98f]" name="bfClass" is-config="true" duration-ms="32" started-at="2022-01-21T00:30:55Z" finished-at="2022-01-21T00:30:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfClass -->
        <test-method status="PASS" signature="setInvalidEmails()[pri:0, instance:automation.GeneralTest@5025a98f]" name="setInvalidEmails" is-config="true" duration-ms="2" started-at="2022-01-21T00:30:55Z" finished-at="2022-01-21T00:30:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setInvalidEmails -->
        <test-method status="PASS" signature="setValidEmails()[pri:0, instance:automation.GeneralTest@5025a98f]" name="setValidEmails" is-config="true" duration-ms="0" started-at="2022-01-21T00:30:55Z" finished-at="2022-01-21T00:30:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setValidEmails -->
        <test-method status="PASS" signature="setInvalidPhones()[pri:0, instance:automation.GeneralTest@5025a98f]" name="setInvalidPhones" is-config="true" duration-ms="0" started-at="2022-01-21T00:30:55Z" finished-at="2022-01-21T00:30:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setInvalidPhones -->
        <test-method status="PASS" signature="setValidPhones()[pri:0, instance:automation.GeneralTest@5025a98f]" name="setValidPhones" is-config="true" duration-ms="1" started-at="2022-01-21T00:30:55Z" finished-at="2022-01-21T00:30:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setValidPhones -->
        <test-method status="PASS" signature="apositiveTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="apositiveTest" duration-ms="21995" started-at="2022-01-21T00:30:55Z" finished-at="2022-01-21T00:31:17Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- apositiveTest -->
        <test-method status="PASS" signature="bpositiveTestSecond()[pri:0, instance:automation.GeneralTest@5025a98f]" name="bpositiveTestSecond" duration-ms="13064" started-at="2022-01-21T00:31:17Z" finished-at="2022-01-21T00:31:30Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- bpositiveTestSecond -->
        <test-method status="PASS" signature="cnegativeTestFirst()[pri:0, instance:automation.GeneralTest@5025a98f]" name="cnegativeTestFirst" duration-ms="12346" started-at="2022-01-21T00:31:30Z" finished-at="2022-01-21T00:31:42Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- cnegativeTestFirst -->
        <test-method status="PASS" signature="dnegativeTestSecond()[pri:0, instance:automation.GeneralTest@5025a98f]" name="dnegativeTestSecond" duration-ms="8328" started-at="2022-01-21T00:31:42Z" finished-at="2022-01-21T00:31:50Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- dnegativeTestSecond -->
        <test-method status="FAIL" signature="eighthInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="eighthInvalidEmailTest" duration-ms="9782" started-at="2022-01-21T00:31:50Z" finished-at="2022-01-21T00:32:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Email:<email@domain.com>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Email:<email@domain.com>
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.eighthInvalidEmailTest(GeneralTest.java:501)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:&lt;email@domain.com&gt;]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- eighthInvalidEmailTest -->
        <test-method status="PASS" signature="eighthValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="eighthValidEmailTest" duration-ms="9309" started-at="2022-01-21T00:32:00Z" finished-at="2022-01-21T00:32:10Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- eighthValidEmailTest -->
        <test-method status="PASS" signature="eleventhInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="eleventhInvalidEmailTest" duration-ms="12645" started-at="2022-01-21T00:32:10Z" finished-at="2022-01-21T00:32:22Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- eleventhInvalidEmailTest -->
        <test-method status="PASS" signature="eleventhValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="eleventhValidEmailTest" duration-ms="9643" started-at="2022-01-21T00:32:22Z" finished-at="2022-01-21T00:32:32Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- eleventhValidEmailTest -->
        <test-method status="FAIL" signature="enegativeTestWithSpacesInName()[pri:0, instance:automation.GeneralTest@5025a98f]" name="enegativeTestWithSpacesInName" duration-ms="9423" started-at="2022-01-21T00:32:32Z" finished-at="2022-01-21T00:32:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Name only contains spaces]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Name only contains spaces
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.enegativeTestWithSpacesInName(GeneralTest.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Name only contains spaces]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- enegativeTestWithSpacesInName -->
        <test-method status="PASS" signature="fifthInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="fifthInvalidEmailTest" duration-ms="8562" started-at="2022-01-21T00:32:41Z" finished-at="2022-01-21T00:32:50Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- fifthInvalidEmailTest -->
        <test-method status="PASS" signature="fifthValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="fifthValidEmailTest" duration-ms="13482" started-at="2022-01-21T00:32:50Z" finished-at="2022-01-21T00:33:03Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- fifthValidEmailTest -->
        <test-method status="PASS" signature="firstInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="firstInvalidEmailTest" duration-ms="12257" started-at="2022-01-21T00:33:03Z" finished-at="2022-01-21T00:33:16Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- firstInvalidEmailTest -->
        <test-method status="FAIL" signature="firstInvalidphoneTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="firstInvalidphoneTest" duration-ms="9546" started-at="2022-01-21T00:33:16Z" finished-at="2022-01-21T00:33:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Phone:+905552+133]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Phone:+905552+133
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.firstInvalidphoneTest(GeneralTest.java:956)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Phone:+905552+133]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- firstInvalidphoneTest -->
        <test-method status="PASS" signature="firstValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="firstValidEmailTest" duration-ms="12968" started-at="2022-01-21T00:33:25Z" finished-at="2022-01-21T00:33:38Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- firstValidEmailTest -->
        <test-method status="PASS" signature="firstValidphoneTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="firstValidphoneTest" duration-ms="9380" started-at="2022-01-21T00:33:38Z" finished-at="2022-01-21T00:33:48Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- firstValidphoneTest -->
        <test-method status="FAIL" signature="fnegativeTestWithSpacesInAddress()[pri:0, instance:automation.GeneralTest@5025a98f]" name="fnegativeTestWithSpacesInAddress" duration-ms="9261" started-at="2022-01-21T00:33:48Z" finished-at="2022-01-21T00:33:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Address only contains spaces]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Address only contains spaces
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.fnegativeTestWithSpacesInAddress(GeneralTest.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Address only contains spaces]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- fnegativeTestWithSpacesInAddress -->
        <test-method status="PASS" signature="fourthInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="fourthInvalidEmailTest" duration-ms="9073" started-at="2022-01-21T00:33:57Z" finished-at="2022-01-21T00:34:06Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- fourthInvalidEmailTest -->
        <test-method status="PASS" signature="fourthValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="fourthValidEmailTest" duration-ms="13313" started-at="2022-01-21T00:34:06Z" finished-at="2022-01-21T00:34:19Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- fourthValidEmailTest -->
        <test-method status="PASS" signature="gnegativeTestWithSpacesInMail()[pri:0, instance:automation.GeneralTest@5025a98f]" name="gnegativeTestWithSpacesInMail" duration-ms="12197" started-at="2022-01-21T00:34:19Z" finished-at="2022-01-21T00:34:31Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- gnegativeTestWithSpacesInMail -->
        <test-method status="PASS" signature="hnegativeTestWrongFormatInMail()[pri:0, instance:automation.GeneralTest@5025a98f]" name="hnegativeTestWrongFormatInMail" duration-ms="8798" started-at="2022-01-21T00:34:31Z" finished-at="2022-01-21T00:34:40Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- hnegativeTestWrongFormatInMail -->
        <test-method status="PASS" signature="inegativeTestAnotherWrongFormatInMail()[pri:0, instance:automation.GeneralTest@5025a98f]" name="inegativeTestAnotherWrongFormatInMail" duration-ms="12836" started-at="2022-01-21T00:34:40Z" finished-at="2022-01-21T00:34:53Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- inegativeTestAnotherWrongFormatInMail -->
        <test-method status="PASS" signature="knegativeTestAnotherWrongFormatInMail()[pri:0, instance:automation.GeneralTest@5025a98f]" name="knegativeTestAnotherWrongFormatInMail" duration-ms="12504" started-at="2022-01-21T00:34:53Z" finished-at="2022-01-21T00:35:06Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- knegativeTestAnotherWrongFormatInMail -->
        <test-method status="PASS" signature="lnegativeTestAnotherWrongFormatInMail()[pri:0, instance:automation.GeneralTest@5025a98f]" name="lnegativeTestAnotherWrongFormatInMail" duration-ms="12349" started-at="2022-01-21T00:35:06Z" finished-at="2022-01-21T00:35:18Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- lnegativeTestAnotherWrongFormatInMail -->
        <test-method status="PASS" signature="mnegativeTestAnotherWrongFormatInMail()[pri:0, instance:automation.GeneralTest@5025a98f]" name="mnegativeTestAnotherWrongFormatInMail" duration-ms="12202" started-at="2022-01-21T00:35:18Z" finished-at="2022-01-21T00:35:30Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- mnegativeTestAnotherWrongFormatInMail -->
        <test-method status="PASS" signature="ninethInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="ninethInvalidEmailTest" duration-ms="12823" started-at="2022-01-21T00:35:30Z" finished-at="2022-01-21T00:35:43Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- ninethInvalidEmailTest -->
        <test-method status="FAIL" signature="ninethValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="ninethValidEmailTest" duration-ms="12251" started-at="2022-01-21T00:35:43Z" finished-at="2022-01-21T00:35:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form wasn't submitted, but it should be submitted. Email:email@[123.123.123.123]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form wasn't submitted, but it should be submitted. Email:email@[123.123.123.123]
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLog(GeneralTest.java:607)
	at automation.GeneralTest.ninethValidEmailTest(GeneralTest.java:796)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form wasn't submitted, but it should be submitted Email:email@[123.123.123.123]]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- ninethValidEmailTest -->
        <test-method status="FAIL" signature="secondInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="secondInvalidEmailTest" duration-ms="9708" started-at="2022-01-21T00:35:55Z" finished-at="2022-01-21T00:36:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Email:.email@domain.com]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Email:.email@domain.com
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.secondInvalidEmailTest(GeneralTest.java:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:.email@domain.com]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- secondInvalidEmailTest -->
        <test-method status="FAIL" signature="secondInvalidphoneTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="secondInvalidphoneTest" duration-ms="10653" started-at="2022-01-21T00:36:05Z" finished-at="2022-01-21T00:36:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Phone:055Letter511223365]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Phone:055Letter511223365
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.secondInvalidphoneTest(GeneralTest.java:977)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Phone:055Letter511223365]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- secondInvalidphoneTest -->
        <test-method status="FAIL" signature="secondValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="secondValidEmailTest" duration-ms="12239" started-at="2022-01-21T00:36:16Z" finished-at="2022-01-21T00:36:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form wasn't submitted, but it should be submitted. Email:"email"@domain.com]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form wasn't submitted, but it should be submitted. Email:"email"@domain.com
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLog(GeneralTest.java:607)
	at automation.GeneralTest.secondValidEmailTest(GeneralTest.java:663)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form wasn't submitted, but it should be submitted Email:"email"@domain.com]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- secondValidEmailTest -->
        <test-method status="PASS" signature="secondValidphoneTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="secondValidphoneTest" duration-ms="13423" started-at="2022-01-21T00:36:28Z" finished-at="2022-01-21T00:36:41Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- secondValidphoneTest -->
        <test-method status="FAIL" signature="seventhInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="seventhInvalidEmailTest" duration-ms="12685" started-at="2022-01-21T00:36:41Z" finished-at="2022-01-21T00:36:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Email:email.@domain.com]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Email:email.@domain.com
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.seventhInvalidEmailTest(GeneralTest.java:482)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:email.@domain.com]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- seventhInvalidEmailTest -->
        <test-method status="PASS" signature="seventhValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="seventhValidEmailTest" duration-ms="9760" started-at="2022-01-21T00:36:54Z" finished-at="2022-01-21T00:37:04Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- seventhValidEmailTest -->
        <test-method status="FAIL" signature="sixthInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="sixthInvalidEmailTest" duration-ms="13258" started-at="2022-01-21T00:37:04Z" finished-at="2022-01-21T00:37:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Email:email..email@domain.com]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Email:email..email@domain.com
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.sixthInvalidEmailTest(GeneralTest.java:463)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:email..email@domain.com]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- sixthInvalidEmailTest -->
        <test-method status="PASS" signature="sixthValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="sixthValidEmailTest" duration-ms="9904" started-at="2022-01-21T00:37:17Z" finished-at="2022-01-21T00:37:27Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- sixthValidEmailTest -->
        <test-method status="PASS" signature="tenthInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="tenthInvalidEmailTest" duration-ms="8767" started-at="2022-01-21T00:37:27Z" finished-at="2022-01-21T00:37:36Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- tenthInvalidEmailTest -->
        <test-method status="PASS" signature="tenthValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="tenthValidEmailTest" duration-ms="9154" started-at="2022-01-21T00:37:36Z" finished-at="2022-01-21T00:37:45Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- tenthValidEmailTest -->
        <test-method status="FAIL" signature="thirdInalidphoneTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="thirdInalidphoneTest" duration-ms="9666" started-at="2022-01-21T00:37:45Z" finished-at="2022-01-21T00:37:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Phone:Letter009055004455]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Phone:Letter009055004455
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.thirdInalidphoneTest(GeneralTest.java:998)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Phone:Letter009055004455]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- thirdInalidphoneTest -->
        <test-method status="PASS" signature="thirdInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="thirdInvalidEmailTest" duration-ms="12391" started-at="2022-01-21T00:37:54Z" finished-at="2022-01-21T00:38:07Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- thirdInvalidEmailTest -->
        <test-method status="PASS" signature="thirdValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="thirdValidEmailTest" duration-ms="9259" started-at="2022-01-21T00:38:07Z" finished-at="2022-01-21T00:38:16Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- thirdValidEmailTest -->
        <test-method status="PASS" signature="thirdValidphoneTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="thirdValidphoneTest" duration-ms="13770" started-at="2022-01-21T00:38:16Z" finished-at="2022-01-21T00:38:30Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- thirdValidphoneTest -->
        <test-method status="PASS" signature="thirteenthInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="thirteenthInvalidEmailTest" duration-ms="8295" started-at="2022-01-21T00:38:30Z" finished-at="2022-01-21T00:38:38Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- thirteenthInvalidEmailTest -->
        <test-method status="PASS" signature="thirteenthValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="thirteenthValidEmailTest" duration-ms="9195" started-at="2022-01-21T00:38:38Z" finished-at="2022-01-21T00:38:47Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- thirteenthValidEmailTest -->
        <test-method status="FAIL" signature="twelwethInvalidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="twelwethInvalidEmailTest" duration-ms="9062" started-at="2022-01-21T00:38:47Z" finished-at="2022-01-21T00:38:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted. Email:email@-domain.com]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed. The form was submitted, but it shouldn't be submitted. Email:email@-domain.com
	at org.testng.Assert.fail(Assert.java:93)
	at automation.GeneralTest.assertAndLogForInvalidInput(GeneralTest.java:622)
	at automation.GeneralTest.twelwethInvalidEmailTest(GeneralTest.java:577)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test is failed. The form was submitted, but it shouldn't be submitted Email:email@-domain.com]]>
            </line>
            <line>
              <![CDATA[Test has failed.
]]>
            </line>
          </reporter-output>
        </test-method> <!-- twelwethInvalidEmailTest -->
        <test-method status="PASS" signature="twelwethValidEmailTest()[pri:0, instance:automation.GeneralTest@5025a98f]" name="twelwethValidEmailTest" duration-ms="13343" started-at="2022-01-21T00:38:56Z" finished-at="2022-01-21T00:39:10Z">
          <reporter-output>
            <line>
              <![CDATA[Test has started. 
]]>
            </line>
            <line>
              <![CDATA[Test has passed. 
]]>
            </line>
          </reporter-output>
        </test-method> <!-- twelwethValidEmailTest -->
      </class> <!-- automation.GeneralTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
